
  CREATE TABLE "ZAWARTOSCI_PRZESYLEK_FK"
   (	"POZYCJA" NUMBER(3,0),
	"NRPRZESYLKI" VARCHAR2(10 CHAR),
	"KODPACZKI" VARCHAR2(10 CHAR),
	"ILOSC" NUMBER(5,0),
	"CENAZAKUPUPACZKI" NUMBER(7,2),
	"WARTOSCPOZYCJI" NUMBER(7,2)
   );

  CREATE GLOBAL TEMPORARY TABLE "TYMCZASOWA_PRZESYLKA_FK"
   (	"NRPRZESYLKI" VARCHAR2(10 BYTE),
	"NRPLATNOSCI" VARCHAR2(10 BYTE),
	"ILEWIERSZY" NUMBER(5,0)
   ) ON COMMIT DELETE ROWS ;

  CREATE TABLE "STATUSY_FK"
   (	"DATA" TIMESTAMP (6),
	"NRPRZESYLKI" VARCHAR2(10 CHAR),
	"STACJA" VARCHAR2(5 CHAR),
	"OPIS" VARCHAR2(200 CHAR)
   );

  CREATE TABLE "STACJE_FK"
   (	"STACJA" VARCHAR2(5 CHAR),
	"NAZWA" VARCHAR2(40 CHAR),
	"KRAJ" VARCHAR2(35 CHAR),
	"MIEJSCOWOSC" VARCHAR2(35 CHAR),
	"KODPOCZTOWY" CHAR(5 CHAR),
	"ULICA" VARCHAR2(30 CHAR),
	"NRBUDYNKU" VARCHAR2(5 CHAR),
	"NRLOKALU" NUMBER(3,0)
   );

  CREATE TABLE "PRZESYLKI_FK"
   (	"NRPRZESYLKI" VARCHAR2(10 CHAR),
	"NRNADAWCY" NUMBER(5,0),
	"NRODBIORCY" NUMBER(5,0),
	"NRPLATNOSCI" VARCHAR2(10 CHAR),
	"ZAWARTOSC" VARCHAR2(500 CHAR),
	"UWAGIDODORECZENIA" VARCHAR2(500 CHAR),
	"KOSZTPRZESYLKI" NUMBER(7,2),
	"KILOMETRY" NUMBER(5,0)
   );

  CREATE TABLE "PLATNOSCI_FK"
   (	"NRPLATNOSCI" VARCHAR2(10 CHAR),
	"NRPLATNIKA" NUMBER(5,0),
	"NRODBIORCY" NUMBER(5,0),
	"KOSZT" NUMBER(7,2),
	"STATUS" VARCHAR2(100 CHAR)
   );

  CREATE TABLE "PACZKI_FK"
   (	"KODPACZKI" VARCHAR2(10 CHAR),
	"NAZWA" VARCHAR2(50 CHAR),
	"WAGA" NUMBER(3,0),
	"WYSOKOSC" NUMBER(3,0),
	"DLUGOSC" NUMBER(3,0),
	"SZEROKOSC" NUMBER(3,0),
	"CENA" NUMBER(5,2)
   );

  CREATE TABLE "KLIENCI_FK"
   (	"NRKLIENTA" NUMBER(5,0),
	"NIPPESEL" VARCHAR2(11 CHAR),
	"NAZWAFIRMY" VARCHAR2(60 CHAR),
	"NAZWISKO" VARCHAR2(40 CHAR),
	"IMIE" VARCHAR2(25 BYTE),
	"KRAJ" VARCHAR2(35 CHAR),
	"MIEJSCOWOSC" VARCHAR2(35 CHAR),
	"KODPOCZTOWY" CHAR(5 BYTE),
	"ULICA" VARCHAR2(30 CHAR),
	"NRBUDYNKU" VARCHAR2(5 CHAR),
	"NRLOKALU" NUMBER(3,0),
	"NRTELEFONU" VARCHAR2(12 CHAR),
	"ADRESEMAIL" VARCHAR2(40 CHAR),
	"RACHUNEKBANKOWY" VARCHAR2(26 CHAR)
   );

  CREATE UNIQUE INDEX "ZAWARTOSC_PRZESYLEK_PK" ON "ZAWARTOSCI_PRZESYLEK_FK" ("NRPRZESYLKI", "POZYCJA");

  CREATE UNIQUE INDEX "STATUSY_PK" ON "STATUSY_FK" ("DATA", "NRPRZESYLKI");

  CREATE UNIQUE INDEX "STACJE_PK" ON "STACJE_FK" ("STACJA");

  CREATE UNIQUE INDEX "PRZESYLKI_PK" ON "PRZESYLKI_FK" ("NRPRZESYLKI");

  CREATE UNIQUE INDEX "PLATNOSCI_PK" ON "PLATNOSCI_FK" ("NRPLATNOSCI");

  CREATE UNIQUE INDEX "PACZKI_PK" ON "PACZKI_FK" ("KODPACZKI");

  CREATE UNIQUE INDEX "KLIENCI_PK" ON "KLIENCI_FK" ("NRKLIENTA");

  CREATE OR REPLACE TRIGGER "AKTUALIZUJ_KWOTE_FK"
after UPDATE of ilosc
ON zawartosci_przesylek_FK
BEGIN

    UPDATE zawartosci_przesylek_FK
    SET wartoscpozycji = ilosc*CENAZAKUPUPACZKI;


END;
/

  CREATE OR REPLACE TRIGGER "AKTUALIZACJA_K_PRZESYLKI_FK" AFTER
insert or update or delete ON zawartosci_przesylek_FK
DECLARE
    v_suma NUMBER;
    v_nrprzesylki przesylki_fk.nrprzesylki%TYPE;
    v_czyjest number;
BEGIN

    SELECT COUNT(*)
    INTO v_czyjest
    FROM tymczasowa_przesylka_FK;

    IF v_czyjest > 0 THEN

    SELECT nrprzesylki
    INTO v_nrprzesylki
    FROM tymczasowa_przesylka_FK
    where rownum < 2;

    END IF;

    SELECT COUNT(*)
    INTO v_czyjest
    FROM zawartosci_przesylek_FK
    WHERE nrprzesylki = v_nrprzesylki;

    IF v_czyjest > 0 THEN

    SELECT SUM(wartoscpozycji)
    INTO v_suma
    FROM zawartosci_przesylek_FK
    WHERE nrprzesylki = v_nrprzesylki;
    end if;

    IF v_suma IS NULL THEN
        v_suma := 0;
    end if;

    UPDATE przesylki_FK
    SET kosztprzesylki = v_suma
    WHERE nrprzesylki = v_nrprzesylki;


END;
/

  CREATE OR REPLACE TRIGGER "AKTUALIZUJ_Z_PRZESYLKI_FK" BEFORE
    INSERT or update or delete ON zawartosci_przesylek_FK
    FOR EACH ROW
DECLARE
    v_suma   NUMBER;
    v_ile number;
BEGIN
    CASE
        WHEN inserting THEN

            SELECT
                COUNT(*)
            INTO
                :new.pozycja
            FROM
                zawartosci_przesylek_FK
            WHERE
                nrprzesylki =:new.nrprzesylki;

            IF
                :new.pozycja = 0
            THEN
                :new.pozycja := 1;
            ELSE
                :new.pozycja :=:new.pozycja + 1;
            END IF;

            SELECT
                cena
            INTO
                :new.cenazakupupaczki
            FROM
                paczki_FK
            WHERE
                kodpaczki =:new.kodpaczki;

            :new.wartoscpozycji :=:new.ilosc *:new.cenazakupupaczki;

              INSERT INTO tymczasowa_przesylka_FK(nrprzesylki)
            values(:new.nrprzesylki);

        WHEN updating THEN

            SELECT
                cena
            INTO
                :new.cenazakupupaczki
            FROM
                paczki_FK
            WHERE
                kodpaczki =:NEW.kodpaczki;

            INSERT INTO tymczasowa_przesylka_FK(nrprzesylki)
            values(:old.nrprzesylki);

        WHEN deleting THEN


            INSERT INTO tymczasowa_przesylka_FK(nrprzesylki)
            values(:old.nrprzesylki);

    END CASE;
END;
/

  CREATE OR REPLACE TRIGGER "GENERUJ_NUMER_PRZESYLKI_FK"
before INSERT ON przesylki_FK
FOR EACH ROW
BEGIN

    IF :NEW.nrprzesylki IS NULL THEN
    SELECT lpad(SEQ_FK_przesylki.NEXTVAL,10,'0')
        INTO :NEW.nrprzesylki
        FROM dual;
    end if;

END;
/

  CREATE OR REPLACE TRIGGER "AKTUALIZACJA_K_PLATNOSCI_FK"
BEFORE UPDATE ON przesylki_FK
FOR EACH ROW
BEGIN
    UPDATE platnosci_FK
        SET koszt = :NEW.kosztprzesylki
        WHERE nrplatnosci = :NEW.nrplatnosci;


END;
/

  CREATE OR REPLACE TRIGGER "GENERUJ_NUMER_PLATNOSCI_FK"
before INSERT ON platnosci_FK
FOR EACH ROW
BEGIN

    IF :NEW.nrplatnosci IS NULL THEN
    SELECT lpad(SEQ_FK_PLATNOSCI.NEXTVAL,10,'0')
        INTO :NEW.nrplatnosci
        FROM dual;
    end if;

END;
/

  CREATE OR REPLACE TRIGGER "GENERUJ_NUMER_KLIENTA_FK"
before INSERT ON klienci_FK
FOR EACH ROW
BEGIN

    IF :NEW.nrklienta IS NULL THEN
    SELECT SEQ_FK_klienci.NEXTVAL
        INTO :NEW.nrklienta
        FROM dual;
    end if;

END;
/

  ALTER TABLE "ZAWARTOSCI_PRZESYLEK_FK" MODIFY ("POZYCJA" NOT NULL );
  ALTER TABLE "ZAWARTOSCI_PRZESYLEK_FK" MODIFY ("NRPRZESYLKI" NOT NULL );
  ALTER TABLE "ZAWARTOSCI_PRZESYLEK_FK" MODIFY ("KODPACZKI" NOT NULL );
  ALTER TABLE "ZAWARTOSCI_PRZESYLEK_FK" MODIFY ("ILOSC" NOT NULL );
  ALTER TABLE "ZAWARTOSCI_PRZESYLEK_FK" MODIFY ("CENAZAKUPUPACZKI" NOT NULL );
  ALTER TABLE "ZAWARTOSCI_PRZESYLEK_FK" MODIFY ("WARTOSCPOZYCJI" NOT NULL );
  ALTER TABLE "ZAWARTOSCI_PRZESYLEK_FK" ADD CONSTRAINT "ZAWARTOSC_PRZESYLEK_PK" PRIMARY KEY ("NRPRZESYLKI", "POZYCJA");

  ALTER TABLE "STATUSY_FK" ADD CONSTRAINT "STATUSY_PK" PRIMARY KEY ("DATA", "NRPRZESYLKI") ;
  ALTER TABLE "STATUSY_FK" MODIFY ("DATA" NOT NULL );
  ALTER TABLE "STATUSY_FK" MODIFY ("NRPRZESYLKI" NOT NULL );
  ALTER TABLE "STATUSY_FK" MODIFY ("STACJA" NOT NULL );
  ALTER TABLE "STATUSY_FK" MODIFY ("OPIS" NOT NULL );

  ALTER TABLE "STACJE_FK" ADD CONSTRAINT "STACJE_PK" PRIMARY KEY ("STACJA") ;
  ALTER TABLE "STACJE_FK" MODIFY ("STACJA" NOT NULL );
  ALTER TABLE "STACJE_FK" MODIFY ("NAZWA" NOT NULL );
  ALTER TABLE "STACJE_FK" MODIFY ("KRAJ" NOT NULL );
  ALTER TABLE "STACJE_FK" MODIFY ("MIEJSCOWOSC" NOT NULL );
  ALTER TABLE "STACJE_FK" MODIFY ("KODPOCZTOWY" NOT NULL );
  ALTER TABLE "STACJE_FK" MODIFY ("ULICA" NOT NULL );
  ALTER TABLE "STACJE_FK" MODIFY ("NRBUDYNKU" NOT NULL );

  ALTER TABLE "PRZESYLKI_FK" ADD CONSTRAINT "PRZESYLKI_PK" PRIMARY KEY ("NRPRZESYLKI") ;
  ALTER TABLE "PRZESYLKI_FK" MODIFY ("NRPRZESYLKI" NOT NULL );
  ALTER TABLE "PRZESYLKI_FK" MODIFY ("NRNADAWCY" NOT NULL );
  ALTER TABLE "PRZESYLKI_FK" MODIFY ("NRODBIORCY" NOT NULL );
  ALTER TABLE "PRZESYLKI_FK" MODIFY ("NRPLATNOSCI" NOT NULL );
  ALTER TABLE "PRZESYLKI_FK" MODIFY ("KOSZTPRZESYLKI" NOT NULL );
  ALTER TABLE "PRZESYLKI_FK" MODIFY ("KILOMETRY" NOT NULL );

  ALTER TABLE "PLATNOSCI_FK" ADD CONSTRAINT "PLATNOSCI_PK" PRIMARY KEY ("NRPLATNOSCI");
  ALTER TABLE "PLATNOSCI_FK" MODIFY ("NRPLATNOSCI" NOT NULL );
  ALTER TABLE "PLATNOSCI_FK" MODIFY ("NRPLATNIKA" NOT NULL );
  ALTER TABLE "PLATNOSCI_FK" MODIFY ("NRODBIORCY" NOT NULL );
  ALTER TABLE "PLATNOSCI_FK" MODIFY ("KOSZT" NOT NULL );
  ALTER TABLE "PLATNOSCI_FK" MODIFY ("STATUS" NOT NULL );

  ALTER TABLE "PACZKI_FK" ADD CONSTRAINT "PACZKI_PK" PRIMARY KEY ("KODPACZKI");
  ALTER TABLE "PACZKI_FK" MODIFY ("KODPACZKI" NOT NULL );
  ALTER TABLE "PACZKI_FK" MODIFY ("NAZWA" NOT NULL );
  ALTER TABLE "PACZKI_FK" MODIFY ("WAGA" NOT NULL );
  ALTER TABLE "PACZKI_FK" MODIFY ("WYSOKOSC" NOT NULL );
  ALTER TABLE "PACZKI_FK" MODIFY ("DLUGOSC" NOT NULL );
  ALTER TABLE "PACZKI_FK" MODIFY ("SZEROKOSC" NOT NULL );
  ALTER TABLE "PACZKI_FK" MODIFY ("CENA" NOT NULL );

  ALTER TABLE "KLIENCI_FK" ADD CONSTRAINT "KLIENCI_PK" PRIMARY KEY ("NRKLIENTA");
  ALTER TABLE "KLIENCI_FK" MODIFY ("NRKLIENTA" NOT NULL );
  ALTER TABLE "KLIENCI_FK" MODIFY ("KRAJ" NOT NULL );
  ALTER TABLE "KLIENCI_FK" MODIFY ("MIEJSCOWOSC" NOT NULL );
  ALTER TABLE "KLIENCI_FK" MODIFY ("KODPOCZTOWY" NOT NULL );
  ALTER TABLE "KLIENCI_FK" MODIFY ("ULICA" NOT NULL );
  ALTER TABLE "KLIENCI_FK" MODIFY ("NRBUDYNKU" NOT NULL );
  ALTER TABLE "KLIENCI_FK" MODIFY ("NRTELEFONU" NOT NULL );
